apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gp8m940lh-nodejs 
  janus-idp.io/tekton: gp8m940lh-nodejs
  backstage.io/kubernetes-id: gp8m940lh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gp8m940lh-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  