apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gp8m940lh-nodejs
  janus-idp.io/tekton: gp8m940lh-nodejs
  backstage.io/kubernetes-id: gp8m940lh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gp8m940lh-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
