apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gp8m940lh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gp8m940lh-nodejs 
  name: gp8m940lh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gp8m940lh-nodejs 
